server:
  port: 8086
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/palSuman97/service-discovery-common-config.git
          clone-on-start: true
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS_DOCKER:http://localhost:8761/eureka}
      
